src/FeedIo/Adapter/Guzzle/Response.php

@alexdebril requested this pull request.
It consists of patches automatically generated for this project on Scrutinizer:
https://scrutinizer-ci.com/g/alexdebril/feed-io/

Scrutinizer Auto-Fixes

---

.travis.yml
composer.json
src/FeedIo/Adapter/Guzzle/Client.php
src/FeedIo/Adapter/Guzzle/Response.php
src/FeedIo/Feed/Node.php
tests/FeedIo/Adapter/Guzzle/ClientTest.php
tests/FeedIo/Feed/ItemTest.php

feed-io now depends on PHP 5.5+ and Guzzle 6

Dependencies upgrade

---

src/FeedIo/Feed/Node.php

see https://github.com/alexdebril/FeedIoBundle/issues/6

resolves sintax problem for several php versions

---

README.md
composer.json
composer.lock
examples/factory.php
src/FeedIo/Factory.php
src/FeedIo/Factory/Builder/GuzzleClientBuilder.php
src/FeedIo/Factory/Builder/MonologBuilder.php
src/FeedIo/Factory/Builder/NullLoggerBuilder.php
src/FeedIo/Factory/BuilderInterface.php
src/FeedIo/Factory/ClientBuilderInterface.php
src/FeedIo/Factory/LoggerBuilderInterface.php
src/FeedIo/Factory/MissingDependencyException.php
tests/FeedIo/Factory/Builder/GuzzleClientBuilderTest.php
tests/FeedIo/Factory/Builder/MonologBuilderTest.php
tests/FeedIo/Factory/Builder/NullLoggerBuilderTest.php
tests/FeedIo/FactoryTest.php

This class makes FeedIo more easy to initialise

Factory class

---

composer.json
composer.lock

close https://github.com/alexdebril/feed-io/issues/29

Update Guzzle to 6.2

---

.travis.yml

PHP 7.0 support

---

README.md

The example PHP code doesn't actually do anything - this PR adds the echo so that the example can be copy and pasted and produce "something" as output :)

Make the example output something correctly

---

src/FeedIo/Rule/Description.php

issue #55 CDATA support 

---

src/FeedIo/Feed/ElementsAwareTrait.php
src/FeedIo/Feed/Node.php
src/FeedIo/Feed/Node/Element.php
src/FeedIo/Feed/Node/ElementInterface.php
src/FeedIo/Rule/OptionalField.php
tests/FeedIo/Feed/ElementsAwareClass.php
tests/FeedIo/Feed/ElementsAwareTraitTest.php
tests/FeedIo/Feed/NodeTest.php
tests/FeedIo/Rule/OptionalFieldTest.php

Implementation of the problem, described in #76

Parse sub-elements of optional fields and make them accessible

---

tests/FeedIo/FactoryTest.php

Add a NullLogger to mute logs

---

src/FeedIo/Feed.php
src/FeedIo/FeedInterface.php
tests/FeedIo/FeedTest.php

Add items countability to feed

---

src/FeedIo/Adapter/FileSystem/Response.php
src/FeedIo/Adapter/Guzzle/Client.php
src/FeedIo/Adapter/Guzzle/Response.php
src/FeedIo/Adapter/NullResponse.php
src/FeedIo/Adapter/ResponseInterface.php
src/FeedIo/Reader.php
tests/FeedIo/FeedIoTest.php
tests/FeedIo/ReaderTest.php

Status 304 support

---

src/FeedIo/Standard/Rss.php
tests/FeedIo/Parser/RssTest.php
tests/samples/rss/rss-with-dc-creator.xml

Added dc:creator as an alias of the Author

---

src/FeedIo/Rule/Description.php

Backport and close #161

---

src/FeedIo/Feed/Item/Media.php
src/FeedIo/Feed/Item/MediaInterface.php
src/FeedIo/Rule/Media.php

Add property name to Media in order to distinct enclosure from thumbnail.

Add property name to Media

---

doc/specifications-support.md
src/FeedIo/Feed.php
src/FeedIo/FeedInterface.php
src/FeedIo/Rule/Language.php
src/FeedIo/Standard/Atom.php
src/FeedIo/Standard/Rss.php
tests/FeedIo/StandardFormatter/FormatterTestAbstract.php
tests/samples/expected-atom.xml
tests/samples/rss/expected-rss.xml

Since I need the PHP 5.6 support myself (unfortunately) I based this on the 3.0 branch. If it's needed I'm fine with making PRs for master as well.

Add support for language/lang

---

src/FeedIo/Standard/Rss.php
tests/FeedIo/StandardFormatter/FormatterTestAbstract.php
tests/samples/expected-atom.xml
tests/samples/rss/expected-rss.xml

Put RSS elements at the right place

---

src/FeedIo/Standard/Rss.php

Fix the alias issue #192

---

src/FeedIo/Reader/Document.php

Remove invalid characters #193

---

src/FeedIo/Adapter/Guzzle/Response.php
tests/FeedIo/Adapter/Guzzle/ClientTest.php

Following #204 : bugfix provided by @Grotax + PHPUnit fix

Grotax grotax patch 1

---

src/FeedIo/FeedIo.php
src/FeedIo/Rule/DateTimeBuilder.php
src/FeedIo/Rule/DateTimeBuilderInterface.php

close https://github.com/alexdebril/feed-io/issues/214

DateBuilder provided through dependency injection

---

src/FeedIo/Rule/Description.php

Support CDATA with leading spaces

---

src/FeedIo/Standard/Atom.php
src/FeedIo/Standard/Rss.php

I have applied the fix from https://github.com/nextcloud/news/issues/537#issuecomment-535395977 to Rss and Atom as well. On my Nextcloud News that fixes the problem mentioned in https://github.com/nextcloud/news/issues/537#issuecomment-537651580

Fix for TypeError

---

src/FeedIo/Formatter/JsonFormatter.php
src/FeedIo/Parser/JsonParser.php
tests/FeedIo/JsonFormatterTest.php
tests/FeedIo/Parser/JsonParserTest.php
tests/samples/feed.json

Add support for Icon in JSON feed

---

composer.json
composer.lock
src/FeedIo/Command/DiscoverCommand.php
src/FeedIo/Command/ReadCommand.php
tests/FeedIo/JsonFormatterTest.php

Hey,
I really like your lib, and wanted to use it with a Symfony 5 application.
Since you only use Console component the diff is pretty small.
You can find the [changelog here](https://github.com/symfony/console/blob/master/CHANGELOG.md)
Cheers,

Symfony 5 support

---

src/FeedIo/Feed/Item/Media.php

I suppose that should fix #252 :)

Deprecated isThumbnail

---

src/FeedIo/FeedIo.php
src/FeedIo/Reader/Fixer/HttpLastModified.php
src/FeedIo/Standard/Rss.php
tests/live-feeds/StandardFeedsTest.php
tests/samples/rss/expected-rss.xml

Don't use aliases nor http-last-modified to set the feed's last modified

---

src/FeedIo/FeedIo.php
src/FeedIo/Reader/Fixer/LastModifiedSince.php
tests/FeedIo/Reader/Fixer/LastModifiedSinceTest.php

Use `modifiedSince` given by the user to fix #266

---

src/FeedIo/Adapter/Guzzle/Response.php

use `strlen` to get the stream's size

---

composer.json
composer.lock

Just updated the dependency. Ran the tests after installing Guzzle 7 and it was all green.

Added Guzzle 7 as a possible dependency

---

src/FeedIo/Rule/Atom/Link.php

Select link with rel="alternate" in priority

---

src/FeedIo/Adapter/Guzzle/Client.php

Accept gzip and deflate encodings

---

src/FeedIo/Reader.php
tests/FeedIo/ReaderTest.php

some publication dates can be set before computers invention

---

src/FeedIo/Rule/Image.php
src/FeedIo/Standard/Rss.php
tests/FeedIo/Rule/ImageTest.php

support unspecified 'image' tag

---

src/FeedIo/Factory.php

Deprecate the factory
