alexdebril/feed-io

- src/FeedIo/Rule/Description.php
Fix this Exception when the feed description tag is empty:
```
InvalidArgumentException: malformed xml string. parsing error : Trying to get property of non-object (8) in /vendor/debril/feed-io/src/FeedIo/Reader.php:95
Stack trace:
#0 vendor/debril/feed-io/src/FeedIo/Rule/Description.php(26): FeedIo\Reader->FeedIo\{closure}(8, 'Trying to get p...', '...', 26, Array)
```
> Fix InvalidArgumentException

- src/FeedIo/Feed/ElementsAwareInterface.php
- src/FeedIo/Feed/ElementsAwareTrait.php
- src/FeedIo/Feed/Node.php
- src/FeedIo/Feed/Node/Element.php
- src/FeedIo/Feed/Node/ElementInterface.php
- src/FeedIo/Feed/NodeInterface.php
Node and Element use ElementsAwareTrait, which implements methods that handles an Iterator of Element's. I Added a ElementsAwareInterface that's implemented by Node and Element. This allows the dev to use it for type hinting or regular instanceof checks in various situations.
It also fixes a conflict with the getValue($name) method added to the Element class by the ElementsAwareTrait and the getValue that was already a method of the Element class.
> Refactor node and element implement a ElementsAwareInterface interface for type checking

- src/FeedIo/Factory.php
- src/FeedIo/Factory/Builder/GuzzleClientBuilder.php
- src/FeedIo/Factory/Builder/NullLoggerBuilder.php
- tests/FeedIo/Factory/Builder/MonologBuilderTest.php
- tests/FeedIo/FactoryTest.php
Resolves #105 
There are couple of assumptions made or inherited by previous design (which I need to preserve for BC purposes):
- all builders (internal or external) need to have a constructor public with only one required argument - array (config). I'm aware of `newInstanceArgs` vs `newInstance` but checking all cases (is constructor public? does it expect array as a first param? is there only one required param? is that required param on first place?) just to instantiate the builder would be a major overkill. It's rational to expect the user to match builder definition.
- objects references passed inside a config are still preserved. This is important if you pass `handlers` config to Monolog but expect to have their reference outside.
As there is no official codestyle, I tried to follow …
> Fix feedio factory configuration

- src/FeedIo/Command/ReadCommand.php
If $item->getLastModified() === null then $item->getLastModified()->format() throw a fatal error
> Fixed error when lastModified is null

- src/FeedIo/Adapter/Guzzle/Response.php
This fixes:
```
DateTime::createFromFormat() expects parameter 2 to be string, array given
```
The 4.0 branch already includes this change.
> createFromFormat() expects fromat to be a string

- src/FeedIo/Standard/Rss.php
This fixes #211 
It is a backport of #189 to the 3.0 branch.
> backport #189 to 3.x; 'content:encode' as alias of 'description'

- src/FeedIo/Reader/Result.php
> Correct small typo in docblock

- src/FeedIo/Standard/Rdf.php
`$document->getDOMDocument()->documentElement->tagName` can be null
Fix taken from https://github.com/nextcloud/news/issues/537#issuecomment-535395977
> Fix for TypeError

- src/FeedIo/Formatter/XmlFormatter.php
- src/FeedIo/Rule/OptionalField.php
- tests/FeedIo/FormatterTest.php
- tests/FeedIo/Rule/OptionalFieldTest.php
- tests/FeedIo/StandardFormatter/FormatterTestAbstract.php
- tests/samples/expected-atom.xml
- tests/samples/rss/expected-rss.xml
Hey, I'm trying to use feed-io to generate a Google products feed, where each entry can have multiple `g:shipping` fields. This leads to an unexpected behavior, simplified example:
```php
$item = $feed->newItem();
$item->set('g:shipping', 'Standard shipping');
$item->set('g:shipping', 'Two-day delivery');
$feed->add($item)
```
Which leads to the following Atom formatted output:
```xml
<entry>
<g:shipping>Two-day delivery</g:shipping>
<g:shipping>Two-day delivery</g:shipping>
</entry>
```
Instead of both values, we only get the last one - duplicated.
My attempt at fixing this comes in two parts:
- `OptionalField` rule now creates a DOM element for each of the elements on the node instance
- `XmlFormatter::getAllRules` now returns only a single `OptionalField` rule for each unique field to …
> Added support for multiple custom fields with the same name

- doc/specifications-support.md
Supported but not implemented json objects are indicated as wip.
> Update documentation for JSON feed

- composer.lock
Archlinux use php 7.4 by default, so this update is needed for php-cs-fixer to not display this error message while running `pre-commit.sh`:
```
$ ./pre-commit.sh
PHP needs to be a minimum version of PHP 5.6.0 and maximum version of PHP 7.3.*.
PHP needs to be a minimum version of PHP 5.6.0 and maximum version of PHP 7.3.*.
PHPUnit 7.5.17 by Sebastian Bergmann and contributors.
...............................................................  63 / 248 ( 25%)
............................................................... 126 / 248 ( 50%)
............................................................... 189 / 248 ( 76%)
...........................................................     248 / 248 (100%)
Time: 171 ms, Memory: 8.00 MB
```
> Update to php-cs-fixer 2.16.1

- src/FeedIo/Feed/Item/Media.php
- src/FeedIo/Feed/Item/MediaInterface.php
- src/FeedIo/Rule/Media.php
- src/FeedIo/RuleAbstract.php
- src/FeedIo/Standard/Atom.php
- src/FeedIo/Standard/Rss.php
- tests/FeedIo/JsonFormatterTest.php
- tests/FeedIo/Parser/MediaRSSTest.php
- tests/samples/rss/sample-youtube.xml
This is my attempt to solve #240 
It has been a long time since I hacked with PHP so I am not familiar anymore with the nice way to do things. Do not hesitate to tell me if I made dirty things :)
The [Media-RSS](http://www.rssboard.org/media-rss) specification describe a lot of tags, but I just implemented those that are used (and useful) in youtube feeds: title, description, and thumbnail. Youtube provides other interesting metada (number of views etc.) which I might tackle in the future, but for now lets keep it simple :)
Media-RSS `<media:thumbnail>` tags were already supported by feed-io, but I am not comfortable with how it is handled. It looks like feed-io treats `<media:thumbnail>` tags as if it were actually the media, while the specification states that it represents a thumbnail …
> Basic Media-RSS support

- src/FeedIo/FeedIo.php
- src/FeedIo/Reader/Fixer/HttpLastModified.php
- src/FeedIo/Reader/Fixer/LastModified.php
- src/FeedIo/Reader/Fixer/PublicId.php
- src/FeedIo/Reader/FixerAbstract.php
- src/FeedIo/Reader/FixerSet.php
- tests/FeedIo/Reader/Fixer/HttpLastModifiedTest.php
- tests/FeedIo/Reader/Fixer/LastModifiedTest.php
- tests/FeedIo/Reader/Fixer/PublicIdTest.php
- tests/FeedIo/Reader/FixerMock.php
- tests/FeedIo/Reader/FixerSetTest.php
- tests/FeedIo/Reader/ResultMockFactory.php
Found while looking into: https://github.com/nextcloud/news/issues/607
Here is a minimal working example: https://github.com/kesselb/fefe-feed-io
This patch will read the last modified value from the response and pass it to the feed. The last modified fixer will usually workaround this issue for feeds with pub date for the items.
> Read last modified value from response

- src/FeedIo/Filter/ModifiedSince.php
- tests/FeedIo/Filter/ModifiedSinceTest.php
That's somehow a regression of https://github.com/alexdebril/feed-io/pull/259
Before #259 last modified was not available. Now we send the right last modified and the server seems to respond accordingly. But for some feeds no items are added.
https://github.com/alexdebril/feed-io/blob/c651b6fc8952ebf0121bc0cc06ceeb3a69d482cf/src/FeedIo/FeedIo.php#L317-L319
A DateTime object for `$modifiedSince` will add the modified since filter.
https://github.com/alexdebril/feed-io/blob/c651b6fc8952ebf0121bc0cc06ceeb3a69d482cf/src/FeedIo/Filter/ModifiedSince.php#L37-L44
Filter will return true if pubDate (or lastBuildDate or lastPubDate) are greater then `$modifiedSince` and false otherwise. As per https://validator.w3.org/feed/docs/rss2.html seems to be a optional property.
Steps to reproduce with …
> A item without pubDate seems to be valid.

- composer.json
- composer.lock
- src/FeedIo/Http/ResponseBuilder.php
- tests/FeedIo/Http/ResponseBuilderTest.php
Fixes `Call to a member function format() on null` on `ResponseBuilder::createResponse` when the given feed is empty (see error below on symfony app).
Also a few other small inspection fixes on the test file the new test is at.
* Fix `ResponseBuilder::createResponse` error when feed has no last modified (eg feed is new)
* Require `ext-dom` in composer as we use it explicitly
* Remove assertions that `createResponse` returns a psr response object: the method signature already enforces this (`createResponse([...]) : ResponseInterface`)
* phpunit already has an assertion to check a string is json, no need to use `assertInternalType` which is also deprecated
> Fix hard error on createResponse when feed has no lastModifiedDate

- src/FeedIo/RuleAbstract.php
- tests/FeedIo/Rule/Atom/AuthorTest.php
Currently if you try to load feeds from Atom which has namespace like 
```xml
<feed xmlns="http://www.w3.org/2005/Atom" xml:lang="en">
<author>
<name>Example</name>
</author>
</feed>
```
It will return `null` for Author fields because it looks in empty `''` namespace.
This PR fixes that.
> Fix Author for namespaced Atom

- src/FeedIo/Feed.php
- src/FeedIo/Feed/ArrayableInterface.php
- src/FeedIo/Feed/Item/Author.php
- src/FeedIo/Feed/Item/Media.php
- src/FeedIo/Feed/Node.php
- tests/FeedIo/Feed/ItemTest.php
- tests/FeedIo/JsonFormatterTest.php
- tests/FeedIo/Parser/JsonParserTest.php
Currently `$feed->toArray()` would make array only first level and would leave `Author` still as object. This is not good when you want to serialize it in some format because then you would need to know about it's internal structure. This PR changes that so it's converted to array recursively including all nested objects. This allows to serialize a feed very easily, eg. `serialize($feed->toArray())`
> Implement recursive toArray

- src/FeedIo/Rule/DateTimeBuilder.php
This change allows parsing dates of the form "Thurs, 11 Oct 2012".
Fixes https://github.com/alexdebril/feed-io/issues/302.
> Add another malformed date format

- src/FeedIo/Reader/Document.php
When the `InvalidArgumentException` thrown by the error handler gets caught, the error handler will never be restored which results in weird error messages for any following error. By using `try ... finally` the handler wil be restored in either case.
> Make sure to restore the error handler

- README.md
I read the entire README.md and this typo
was the only one I found.
> Fix logical typo in README.md

- src/FeedIo/FeedIo.php
- src/FeedIo/Http/ResponseBuilder.php
- src/FeedIo/Standard/Atom.php
- src/FeedIo/Standard/Json.php
- src/FeedIo/Standard/Rdf.php
- src/FeedIo/Standard/Rss.php
- src/FeedIo/StandardAbstract.php
- tests/FeedIo/Http/ResponseBuilderTest.php
This is the PR for #393 
I ended up adding the mime type to the standard and then passing it from there directly to the response builder. The advantage being that any custom standard will be supported. It is a breaking change though. Alternatively, I could just resubmit a PR with just a regular match statement within `ResponseBuilder::createResponse()`.
> Added more consice mime types to default standards

- src/FeedIo/Explorer.php
- tests/FeedIo/ExplorerTest.php
- tests/samples/discovery-dualprotocol.html
- tests/samples/discovery-https.html
Some websites will omit the http/https protocol from links within the document, allowing the browser to request the feed via http or https depending on which protocol the page itself was fetched via. 
The discover functionality of FeedIO does not apply a protocol to such links, but downstream consumers, such as Nextcloud news, will assume that discovered feeds include the protocol.
This commit alters FeedIO so that it assigns the https protocol to such discovered feeds that do not include the protocol in their link, allowing downstream consumers to maintain their assumption that discovered feeds will include a feed without breaking compatibility with the source feed, unless the source feed violates the assumption that a link href that omits the protocol can be fetched via either http or …
> Improve handling of feeds when discover encounters feed links without protocol

- src/FeedIo/Rule/Link.php
Some RSS feeds specify links using an atom-like format, specifically as `<link rel="alternate" type="text/html" href="URL"></link>`
This PR attempts to add support for reading such links.
> Workaround for atom-like links in RSS feeds

- src/FeedIo/Explorer.php
- src/FeedIo/Feed.php
- src/FeedIo/Feed/Node.php
- src/FeedIo/Parser/XmlParser.php
- src/FeedIo/Reader.php
- src/FeedIo/Rule/Link.php
1. Fix: feed discovery with relative URLs in links
2. Fix: relative links in the Title and in Body
Example: https://k47.cz/
Solution to the problem: #417
Solution to the problem: #418
> Fix: Relative links

- src/FeedIo/Explorer.php
- src/FeedIo/Feed.php
- src/FeedIo/Feed/Node.php
- src/FeedIo/Parser/XmlParser.php
- src/FeedIo/Reader.php
- src/FeedIo/Rule/Link.php
- Fix: feed discovery with relative URLs in links
Example: https://k47.cz/
- Fix: relative links in the Title and in Body
Solution to the problem: 
https://github.com/alexdebril/feed-io/issues/417
https://github.com/alexdebril/feed-io/issues/418
https://github.com/nextcloud/news/issues/1952
https://github.com/nextcloud/news/issues/1605
> Fix: Release/5.3.x Support relative links
